version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      swapper-deps:
        patterns:
          - "@mayanfinance/*"
          - "@orca-so/*"
          - "@ston-fi/*"
          - "@cetusprotocol/*"
          - "@panoraexchange/*"
