version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@mysten/sui"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@solana/kit"
        update-types:
          - "version-update:semver-major"
    groups:
      swapper-deps:
        patterns:
          - "@mayanfinance/*"
          - "@orca-so/*"
          - "@ston-fi/*"
          - "@cetusprotocol/*"
          - "@panoraexchange/*"
