/*
 Generated by typeshare 1.13.3
*/

import { QuoteAsset } from "./Approval";

export interface ProxyQuoteRequest {
	from_address: string;
	to_address: string;
	from_asset: QuoteAsset;
	to_asset: QuoteAsset;
	from_value: string;
	referral_bps: number;
	slippage_bps: number;
	use_max_amount: boolean;
}

export interface ProxyQuote {
	quote: ProxyQuoteRequest;
	output_value: string;
	output_min_value: string;
	route_data: object;
	eta_in_seconds: number;
}

