/*
 Generated by typeshare 1.13.3
*/

export enum SwapProvider {
	UniswapV3 = "uniswap_v3",
	UniswapV4 = "uniswap_v4",
	PancakeswapV3 = "pancakeswap_v3",
	Aerodrome = "aerodrome",
	PancakeswapAptosV2 = "pancakeswap_aptos_v2",
	Thorchain = "thorchain",
	Jupiter = "jupiter",
	Across = "across",
	Oku = "oku",
	Wagmi = "wagmi",
	Cetus = "cetus",
	StonfiV2 = "stonfi_v2",
	Mayan = "mayan",
	Reservoir = "reservoir",
	Chainflip = "chainflip",
	NearIntents = "near_intents",
	CetusAggregator = "cetus_aggregator",
	Relay = "relay",
	Hyperliquid = "hyperliquid",
	Orca = "orca",
}

