/*
 Generated by typeshare 1.13.3
*/

export enum SwapProvider {
	UniswapV3 = "uniswap_v3",
	UniswapV4 = "uniswap_v4",
	PancakeswapV3 = "pancakeswap_v3",
	Aerodrome = "aerodrome",
	Panora = "panora",
	Thorchain = "thorchain",
	Jupiter = "jupiter",
	Okx = "okx",
	Across = "across",
	Oku = "oku",
	Wagmi = "wagmi",
	StonfiV2 = "stonfi_v2",
	Mayan = "mayan",
	Chainflip = "chainflip",
	NearIntents = "near_intents",
	CetusAggregator = "cetus_aggregator",
	Relay = "relay",
	Hyperliquid = "hyperliquid",
	Squid = "squid",
}
