name: Publish Containers

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      target:
        description: "Container to build"
        required: false
        default: all
        type: choice
        options:
          - all
          - swapper

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare image name
        run: |
          echo "SWAPPER_IMAGE=$(echo ghcr.io/${GITHUB_REPOSITORY}/swapper | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_GITHUB_TOKEN }}

      - name: Build and push swapper image
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target == 'all' || github.event.inputs.target == 'swapper' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha,scope=swapper
          cache-to: type=gha,scope=swapper,mode=max
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          tags: |
            ${{ env.SWAPPER_IMAGE }}:latest
            ${{ env.SWAPPER_IMAGE }}:${{ github.sha }}
